# Generated by Django 4.2.16 on 2024-09-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stat_delete_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='is_admin_generated',
            field=models.BooleanField(default=False),
        ),
    ]
