# Generated by Django 4.2.16 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_stat_description_stat_is_admin_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
    ]
