# Generated by Django 4.2.16 on 2024-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0004_alter_message_receiver_group_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='custom_messages/group_photos/'),
        ),
    ]
