# Generated by Django 4.2.16 on 2024-09-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='requester',
            new_name='user',
        ),
    ]
