# Generated by Django 4.2.16 on 2024-09-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_document_product_video_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='user',
        ),
    ]
